R3147/development
Reactv3/awesome-business-cards pull request #8
Opened 2022-11-05 16:29 UTC by lakkaru

2022-11-07 06:06 UTC, radika-react commented
Please change image name from `Lakkaru image.png` to `Lakkaru_image.png`

2022-11-07 12:45 UTC, lakkaru commented
> Please change image name from `Lakkaru image.png` to `Lakkaru_image.png`

Thanks,
Renamed.

2022-11-09 13:45 UTC, Radikad requested changes
in the main index file 
this line 
  <iframe src="./R3050/R3050.html"></iframe>
should be 
  <iframe src="./R3050/index.html"></iframe>

Plase do the necessary changes and push the new changes.
Thank you.

2022-11-09 13:46 UTC, Radikad approved these changes

2022-11-09 13:46 UTC, merged